
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace global
[<assembly: Android.Runtime.ResourceDesignerAttribute("Evaluare.Resource", IsApplication=true)>]
    do ()

namespace Evaluare
    // Generated by F# CodeDom
    #nowarn "49" // uppercase argument names
    #nowarn "67" // this type test or downcast will always hold
    #nowarn "66" // this upcast is unnecessary - the types are identical
    #nowarn "58" // possible incorrect indentation..
    #nowarn "57" // do not use create_DelegateEvent
    #nowarn "51" // address-of operator can occur in the code
    #nowarn "1183" // unused 'this' reference
    
    exception ReturnException732363b0a9af44f1854f304790d5e754 of obj
    exception ReturnNoneException732363b0a9af44f1854f304790d5e754
    [<AutoOpen>]
    module FuncConvertFinalOverload732363b0a9af44f1854f304790d5e754 =
      // This extension member adds to the FuncConvert type and is the last resort member in the method overloading rules. 
      type global.Microsoft.FSharp.Core.FuncConvert with
          /// A utility function to convert function values from tupled to curried form
          static member FuncFromTupled (f:'T -> 'Res) = f
    
    type
        [<System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")>]
        
        (* partial *)Resource () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)
            static member UpdateIdValues  () =
                ()


    
    and
        
        (* partial *)Resource_Attribute () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Drawable () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f020000
            static member Icon = 2130837504
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Id () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f050005
            static member efort_togglebutton = 2131034117
            
            // aapt resource value: 0x7f050004
            static member hEfort = 2131034116
            
            // aapt resource value: 0x7f05000c
            static member height = 2131034124
            
            // aapt resource value: 0x7f05000b
            static member imc = 2131034123
            
            // aapt resource value: 0x7f050008
            static member m500 = 2131034120
            
            // aapt resource value: 0x7f05000a
            static member myButton = 2131034122
            
            // aapt resource value: 0x7f05000e
            static member myButton2 = 2131034126
            
            // aapt resource value: 0x7f050009
            static member p500 = 2131034121
            
            // aapt resource value: 0x7f05000d
            static member proteic = 2131034125
            
            // aapt resource value: 0x7f050006
            static member rma = 2131034118
            
            // aapt resource value: 0x7f050001
            static member rmb = 2131034113
            
            // aapt resource value: 0x7f050007
            static member rmt = 2131034119
            
            // aapt resource value: 0x7f050002
            static member sex_togglebutton = 2131034114
            
            // aapt resource value: 0x7f050000
            static member textView1 = 2131034112
            
            // aapt resource value: 0x7f050003
            static member textView2 = 2131034115
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Layout () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f030000
            static member Main = 2130903040
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_String () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f040001
            static member app_name = 2130968577
            
            // aapt resource value: 0x7f040000
            static member hello = 2130968576
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)

